### ISSUE TITLE
How many VIP should be used in SAPHanaSR-scaleOut?

### ISSUE THREAD

**Issue by JosephLiuBin** [fmherschel/SAPHanaSR-scaleOut-fh#1]
Hello,

Would you please kindly let me know how many VIP should be used in SAPHanaSR-scaleOut? Only master node? Only 3 master nameserver candidates? All nodes?

Thanks and best Regards,
Joseph Liu

**Comment by fmherschel** [comment]
Only one virtual IP adress. This will be moved to an other master nameserver candidate when ever the real master name server switches from one node to an other.
